// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// DBFactory is an autogenerated mock type for the DBFactory type
type DBFactory struct {
	mock.Mock
}

// Commit provides a mock function with given fields: tx
func (_m *DBFactory) Commit(tx *gorm.DB) {
	_m.Called(tx)
}

// GetDB provides a mock function with given fields:
func (_m *DBFactory) GetDB() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// GetDBWithTx provides a mock function with given fields:
func (_m *DBFactory) GetDBWithTx() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Rollback provides a mock function with given fields: tx
func (_m *DBFactory) Rollback(tx *gorm.DB) {
	_m.Called(tx)
}
