version: '3.1'

services:
  mydb:
    image: mysql:8.0.25
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wager-mgmt-integration
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '3307:3306'
