version: '3.8'
x-wager-common:
  &wager-common
  image: ${WAGER_APP_IMAGE_NAME:-wager-management-be:local}
  # build: .
  environment:
    &wager-common-env
    LOG_MODE: production
    LOG_LEVEL: INFO
    GIN_MODE: release
    DB_NAME: wager-mgmt
    DB_USER: dev
    DB_PASSWORD: dev
    DB_ADDRESS: mydb:3306

services:
  mydb:
    image: mysql:8.0.25
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wager-mgmt
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - '3306:3306'
    volumes:
      - dbstorage:/var/lib/mysql

  wager-app:
    <<: *wager-common
    restart: always
    depends_on:
    - mydb
    ports:
    - "8080:8080"

  wager-migration:
    <<: *wager-common
    restart: on-failure
    entrypoint: ./migrate
    depends_on:
      - wager-app

volumes:
  dbstorage:
