// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/duyquang6/wager-management-be/internal/model"
)

// PurchaseRepository is an autogenerated mock type for the PurchaseRepository type
type PurchaseRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tx, purchase
func (_m *PurchaseRepository) Create(ctx context.Context, tx *gorm.DB, purchase model.Purchase) (model.Purchase, error) {
	ret := _m.Called(ctx, tx, purchase)

	var r0 model.Purchase
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, model.Purchase) model.Purchase); ok {
		r0 = rf(ctx, tx, purchase)
	} else {
		r0 = ret.Get(0).(model.Purchase)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, model.Purchase) error); ok {
		r1 = rf(ctx, tx, purchase)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
